sonar.projectKey=aa-loyalty-legacy
sonar.projectName=AA AAdvantage Loyalty (Legacy)
sonar.projectVersion=3.7.1-SNAPSHOT
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=8
sonar.host.url=http://localhost:9000
sonar.login=sqp_f1d1fd00b8d16bd86ddb03b59f8d7f38a44d1b9f
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes
