sonar.projectKey=citation-auditor-2026-001
sonar.projectName=citation-auditor-2026-001
sonar.projectVersion=0.1.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_461728998d7e609641f4d167827b91318c87cc0e
